"""refactor_schema_to_match_design

Revision ID: 4c84b4fb6cbc
Revises: 82fd145ae26f
Create Date: 2025-11-28 13:53:57.301062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c84b4fb6cbc'
down_revision: Union[str, None] = '82fd145ae26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_files')
    op.drop_table('lecture_metrics')
    with op.batch_alter_table('comment_summaries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('analysis_version')

    with op.batch_alter_table('response_comments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_id')
        batch_op.drop_column('is_important')
        batch_op.drop_column('llm_summary')
        batch_op.drop_column('llm_risk_level')
        batch_op.drop_column('account_name')
        batch_op.drop_column('llm_importance_score')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('survey_batch_id')
        batch_op.drop_column('uploaded_file_id')
        batch_op.drop_column('analysis_version')
        batch_op.drop_column('question_text')

    with op.batch_alter_table('score_distributions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('survey_batches', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('processing_started_at')
        batch_op.drop_column('total_responses')
        batch_op.drop_column('lecture_date')
        batch_op.drop_column('processing_completed_at')
        batch_op.drop_column('period')
        batch_op.drop_column('error_message')
        batch_op.drop_column('course_name')
        batch_op.drop_column('status')
        batch_op.drop_column('lecture_number')
        batch_op.drop_column('uploaded_file_id')
        batch_op.drop_column('academic_year')
        batch_op.drop_column('total_comments')

    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_name')
        batch_op.drop_column('row_index')
        batch_op.drop_column('uploaded_file_id')

    with op.batch_alter_table('survey_summaries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('important_comments_count')
        batch_op.drop_column('comments_count')
        batch_op.drop_column('analysis_version')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_version', sa.VARCHAR(length=20), server_default=sa.text("'preliminary'"), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('important_comments_count', sa.INTEGER(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_file_id', sa.BIGINT(), nullable=False))
        batch_op.add_column(sa.Column('row_index', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'uploaded_files', ['uploaded_file_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('survey_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_comments', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('academic_year', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('uploaded_file_id', sa.BIGINT(), nullable=False))
        batch_op.add_column(sa.Column('lecture_number', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('course_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('period', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('processing_completed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('lecture_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('total_responses', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('processing_started_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(None, 'uploaded_files', ['uploaded_file_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('score_distributions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('response_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_text', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('analysis_version', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('uploaded_file_id', sa.BIGINT(), nullable=False))
        batch_op.add_column(sa.Column('survey_batch_id', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('llm_importance_score', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('llm_risk_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('llm_summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_important', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'uploaded_files', ['uploaded_file_id'], ['id'])
        batch_op.create_foreign_key(None, 'survey_batches', ['survey_batch_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('comment_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_version', sa.VARCHAR(length=20), server_default=sa.text("'preliminary'"), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('lecture_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_file_id', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('zoom_participant_count', sa.INTEGER(), nullable=True),
    sa.Column('recording_view_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uploaded_file_id')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lecture_date', sa.DATE(), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('lecture_number', sa.INTEGER(), nullable=False),
    sa.Column('academic_year', sa.VARCHAR(length=10), nullable=True),
    sa.Column('period', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('total_rows', sa.INTEGER(), nullable=True),
    sa.Column('processed_rows', sa.INTEGER(), nullable=True),
    sa.Column('lecture_id', sa.INTEGER(), nullable=True),
    sa.Column('processing_started_at', sa.DATETIME(), nullable=True),
    sa.Column('processing_completed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('finalized_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
