"""Fix model relationships and columns

Revision ID: 5c5f181bb488
Revises: 202410171200
Create Date: 2025-11-28 13:28:39.175180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5f181bb488'
down_revision: Union[str, None] = '202410171200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_summaries', schema=None) as batch_op:
        batch_op.alter_column('survey_batch_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
        batch_op.alter_column('analysis_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'preliminary'"))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint('uq_comment_summary_entry', type_='unique')

    with op.batch_alter_table('lecture_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zoom_participant_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recording_view_count', sa.Integer(), nullable=True))
        batch_op.alter_column('uploaded_file_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('zoom_participants')
        batch_op.drop_column('recording_views')

    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_on', sa.Date(), nullable=True))
        batch_op.alter_column('instructor_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint('uq_lecture_identity', type_='unique')
        batch_op.create_unique_constraint('uq_lecture_composite', ['academic_year', 'term', 'name', 'session', 'lecture_on'])
        batch_op.drop_column('course_name')
        batch_op.drop_column('period')
        batch_op.drop_column('category')
        batch_op.drop_column('lecture_date')

    with op.batch_alter_table('response_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_importance', sa.String(length=10), nullable=True))
        batch_op.alter_column('survey_response_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('uploaded_file_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('survey_batch_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('llm_importance_score',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=3, scale=2),
               existing_nullable=True)
        batch_op.alter_column('processed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('ix_response_comments_account_id')
        batch_op.drop_index('ix_response_comments_survey_batch_id')
        batch_op.drop_column('llm_importance_level')

    with op.batch_alter_table('score_distributions', schema=None) as batch_op:
        batch_op.alter_column('survey_batch_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
        batch_op.drop_constraint('uq_score_distribution_entry', type_='unique')

    with op.batch_alter_table('survey_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_on', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('zoom_participant_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recording_view_count', sa.Integer(), nullable=True))
        batch_op.alter_column('uploaded_file_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('processing_started_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('processing_completed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('uploaded_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.drop_constraint('uq_survey_batch_identity', type_='unique')
        batch_op.drop_column('zoom_participants')
        batch_op.drop_column('finalized_at')
        batch_op.drop_column('recording_views')
        batch_op.drop_column('lecture_date')

    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_content_volume', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('score_content_understanding', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('score_content_announcement', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('score_instructor_overall', sa.Integer(), nullable=False))
        batch_op.alter_column('uploaded_file_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('survey_batch_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('account_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('score_satisfaction_overall',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score_instructor_time',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score_instructor_qa',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score_instructor_speaking',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score_self_preparation',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score_self_motivation',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score_self_future',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score_recommend_friend',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_survey_responses_account_id')
        batch_op.drop_index('ix_survey_responses_survey_batch_id')
        batch_op.drop_column('score_satisfaction_content_understanding')
        batch_op.drop_column('score_satisfaction_content_announcement')
        batch_op.drop_column('score_satisfaction_instructor_response')
        batch_op.drop_column('score_satisfaction_instructor_efficiency')
        batch_op.drop_column('score_satisfaction_instructor_overall')
        batch_op.drop_column('score_satisfaction_instructor_clarity')
        batch_op.drop_column('score_self_applicability')
        batch_op.drop_column('score_satisfaction_content_volume')

    with op.batch_alter_table('survey_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nps', sa.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('promoter_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passive_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('detractor_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_satisfaction_overall', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('avg_content_volume', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('avg_content_understanding', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('avg_content_announcement', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('avg_instructor_overall', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('avg_instructor_time', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('avg_instructor_qa', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('avg_instructor_speaking', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('avg_self_preparation', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('avg_self_motivation', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('avg_self_future', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.alter_column('survey_batch_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
        batch_op.alter_column('analysis_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'preliminary'"))
        batch_op.alter_column('response_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint('uq_survey_summary_batch_version', type_='unique')
        batch_op.drop_column('score_content_understanding')
        batch_op.drop_column('score_content_announcement')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('score_self_future')
        batch_op.drop_column('score_overall_satisfaction')
        batch_op.drop_column('score_self_preparation')
        batch_op.drop_column('nps_promoters')
        batch_op.drop_column('score_instructor_speaking')
        batch_op.drop_column('score_instructor_overall')
        batch_op.drop_column('score_instructor_qa')
        batch_op.drop_column('nps_total')
        batch_op.drop_column('score_instructor_time')
        batch_op.drop_column('nps_detractors')
        batch_op.drop_column('nps_score')
        batch_op.drop_column('score_self_motivation')
        batch_op.drop_column('nps_passives')
        batch_op.drop_column('score_content_volume')

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_on', sa.Date(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('s3_key',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               nullable=False)
        batch_op.alter_column('uploaded_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('processing_started_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('processing_completed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('finalized_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint('uq_course_lecture_instance', type_='unique')
        batch_op.drop_column('task_id')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('content_type')
        batch_op.drop_column('lecture_date')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('content_type', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('task_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_course_lecture_instance', ['course_name', 'lecture_date', 'lecture_number'])
        batch_op.alter_column('finalized_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('processing_completed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('processing_started_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('s3_key',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('lecture_on')

    with op.batch_alter_table('survey_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_content_volume', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('nps_passives', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_self_motivation', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('nps_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('nps_detractors', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_instructor_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('nps_total', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_instructor_qa', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('score_instructor_overall', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('score_instructor_speaking', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('nps_promoters', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_self_preparation', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('score_overall_satisfaction', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('score_self_future', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('score_content_announcement', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('score_content_understanding', sa.FLOAT(), nullable=True))
        batch_op.create_unique_constraint('uq_survey_summary_batch_version', ['survey_batch_id', 'analysis_version', 'student_attribute'])
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('response_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('analysis_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'preliminary'"))
        batch_op.alter_column('survey_batch_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('avg_self_future')
        batch_op.drop_column('avg_self_motivation')
        batch_op.drop_column('avg_self_preparation')
        batch_op.drop_column('avg_instructor_speaking')
        batch_op.drop_column('avg_instructor_qa')
        batch_op.drop_column('avg_instructor_time')
        batch_op.drop_column('avg_instructor_overall')
        batch_op.drop_column('avg_content_announcement')
        batch_op.drop_column('avg_content_understanding')
        batch_op.drop_column('avg_content_volume')
        batch_op.drop_column('avg_satisfaction_overall')
        batch_op.drop_column('detractor_count')
        batch_op.drop_column('passive_count')
        batch_op.drop_column('promoter_count')
        batch_op.drop_column('nps')

    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_satisfaction_content_volume', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_self_applicability', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_satisfaction_instructor_clarity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_satisfaction_instructor_overall', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_satisfaction_instructor_efficiency', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_satisfaction_instructor_response', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_satisfaction_content_announcement', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('score_satisfaction_content_understanding', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_survey_responses_survey_batch_id', ['survey_batch_id'], unique=False)
        batch_op.create_index('ix_survey_responses_account_id', ['account_id'], unique=False)
        batch_op.alter_column('score_recommend_friend',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score_self_future',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score_self_motivation',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score_self_preparation',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score_instructor_speaking',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score_instructor_qa',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score_instructor_time',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score_satisfaction_overall',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('account_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('survey_batch_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('uploaded_file_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('score_instructor_overall')
        batch_op.drop_column('score_content_announcement')
        batch_op.drop_column('score_content_understanding')
        batch_op.drop_column('score_content_volume')

    with op.batch_alter_table('survey_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('recording_views', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('finalized_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('zoom_participants', sa.INTEGER(), nullable=True))
        batch_op.create_unique_constraint('uq_survey_batch_identity', ['course_name', 'lecture_date', 'lecture_number'])
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('processing_completed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('processing_started_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('uploaded_file_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('recording_view_count')
        batch_op.drop_column('zoom_participant_count')
        batch_op.drop_column('lecture_on')

    with op.batch_alter_table('score_distributions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_score_distribution_entry', ['survey_batch_id', 'student_attribute', 'question_key', 'score_value'])
        batch_op.alter_column('survey_batch_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('response_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_importance_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_index('ix_response_comments_survey_batch_id', ['survey_batch_id'], unique=False)
        batch_op.create_index('ix_response_comments_account_id', ['account_id'], unique=False)
        batch_op.alter_column('processed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('llm_importance_score',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('survey_batch_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('uploaded_file_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('survey_response_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('llm_importance')

    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('period', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('course_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint('uq_lecture_composite', type_='unique')
        batch_op.create_unique_constraint('uq_lecture_identity', ['name', 'academic_year', 'term', 'session', 'lecture_date'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('instructor_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('lecture_on')

    with op.batch_alter_table('lecture_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recording_views', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('zoom_participants', sa.INTEGER(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('uploaded_file_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('recording_view_count')
        batch_op.drop_column('zoom_participant_count')

    with op.batch_alter_table('comment_summaries', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_comment_summary_entry', ['survey_batch_id', 'analysis_version', 'student_attribute', 'analysis_type', 'label'])
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('analysis_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'preliminary'"))
        batch_op.alter_column('survey_batch_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
