"""schema_updates

Revision ID: 82fd145ae26f
Revises: 5c5f181bb488
Create Date: 2025-11-28 13:37:04.480597

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '82fd145ae26f'
down_revision: Union[str, None] = '5c5f181bb488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_summaries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_date', sa.Date(), nullable=True))
        batch_op.drop_constraint('uq_lecture_composite', type_='unique')
        batch_op.create_unique_constraint('uq_lecture_composite', ['academic_year', 'term', 'name', 'session', 'lecture_date'])
        batch_op.drop_column('lecture_on')

    with op.batch_alter_table('response_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_id', sa.BigInteger(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_response_comments_response_id', 'survey_responses', ['response_id'], ['id'])
        batch_op.drop_column('survey_response_id')

    with op.batch_alter_table('score_distributions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('survey_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('zoom_participants', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recording_views', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('zoom_participant_count')
        batch_op.drop_column('recording_view_count')
        batch_op.drop_column('lecture_on')

    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('survey_summaries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_date', sa.Date(), nullable=False))
        batch_op.drop_column('lecture_on')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_on', sa.DATE(), nullable=False))
        batch_op.drop_column('lecture_date')

    with op.batch_alter_table('survey_summaries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('survey_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_on', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('recording_view_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('zoom_participant_count', sa.INTEGER(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('recording_views')
        batch_op.drop_column('zoom_participants')
        batch_op.drop_column('lecture_date')

    with op.batch_alter_table('score_distributions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('response_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_response_id', sa.BIGINT(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_response_comments_survey_response_id', 'survey_responses', ['survey_response_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('response_id')

    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_on', sa.DATE(), nullable=True))
        batch_op.drop_constraint('uq_lecture_composite', type_='unique')
        batch_op.create_unique_constraint('uq_lecture_composite', ['academic_year', 'term', 'name', 'session', 'lecture_on'])
        batch_op.drop_column('lecture_date')

    with op.batch_alter_table('comment_summaries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
