"""restore_llm_prefix

Revision ID: bfe9176e9925
Revises: b2f3d8e9a7c1
Create Date: 2026-01-14 07:19:12.838213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe9176e9925'
down_revision: Union[str, None] = 'b2f3d8e9a7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_sentiment_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('llm_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('llm_priority', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('llm_fix_difficulty', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('llm_is_abusive', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_abusive')
        batch_op.drop_column('fix_difficulty')
        batch_op.drop_column('priority')
        batch_op.drop_column('sentiment_type')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sentiment_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fix_difficulty', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_abusive', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('llm_is_abusive')
        batch_op.drop_column('llm_fix_difficulty')
        batch_op.drop_column('llm_priority')
        batch_op.drop_column('llm_category')
        batch_op.drop_column('llm_sentiment_type')

    # ### end Alembic commands ###
