"""add_uploaded_file_metadata

Revision ID: ca6c48fd97cc
Revises: 
Create Date: 2025-10-19 16:01:20.588001

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca6c48fd97cc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploaded_file",
        sa.Column("file_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("course_name", sa.String(length=255), nullable=False),
        sa.Column("lecture_date", sa.Date(), nullable=False),
        sa.Column("lecture_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("s3_key", sa.String(length=512), nullable=True),
        sa.Column("upload_timestamp", sa.TIMESTAMP(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=True),
        sa.Column("processed_rows", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("file_id"),
        sa.UniqueConstraint(
            "course_name",
            "lecture_date",
            "lecture_number",
            name="uq_course_lecture_instance",
        ),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("score_satisfaction_overall", sa.Integer(), nullable=True),
        sa.Column("comment_text", sa.Text(), nullable=False),
        sa.Column("llm_category", sa.String(length=50), nullable=True),
        sa.Column("llm_sentiment", sa.String(length=20), nullable=True),
        sa.Column("llm_summary", sa.Text(), nullable=True),
        sa.Column("llm_importance_level", sa.String(length=20), nullable=True),
        sa.Column("llm_importance_score", sa.Float(), nullable=True),
        sa.Column("llm_risk_level", sa.String(length=20), nullable=True),
        sa.Column("processed_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["uploaded_file.file_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment")
    op.drop_table("uploaded_file")
    # ### end Alembic commands ###
